<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
body{font-family:Arial,sans-serif;background:#f3f4f6;margin:0;padding:20px;}
.container{max-width:700px;margin:0 auto;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,.08);}
.header{background:#030712;padding:28px 32px;}
.header h1{color:#00f5c4;margin:0;font-size:22px;}
.header p{color:#6b7280;margin:6px 0 0;font-size:13px;}
.summary{display:flex;border-bottom:1px solid #e5e7eb;}
.stat{flex:1;padding:20px;text-align:center;border-right:1px solid #e5e7eb;}
.stat:last-child{border-right:none;}
.stat-num{font-size:28px;font-weight:700;}
.stat-lbl{font-size:11px;color:#6b7280;text-transform:uppercase;letter-spacing:.05em;margin-top:4px;}
.section{padding:24px 32px;}
.section h2{font-size:15px;font-weight:700;color:#111827;margin:0 0 16px;}
table{width:100%;border-collapse:collapse;font-size:13px;}
th{background:#f9fafb;color:#6b7280;font-size:11px;text-transform:uppercase;letter-spacing:.05em;padding:10px 12px;text-align:left;border-bottom:1px solid #e5e7eb;}
td{padding:12px;border-bottom:1px solid #f3f4f6;color:#374151;vertical-align:top;}
.badge{display:inline-block;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:700;text-transform:uppercase;}
.badge-critical{background:#fef2f2;color:#dc2626;}
.badge-high{background:#fff7ed;color:#ea580c;}
.badge-medium{background:#fefce8;color:#ca8a04;}
.badge-low{background:#f0fdf4;color:#16a34a;}
.footer{background:#f9fafb;padding:16px 32px;text-align:center;font-size:12px;color:#9ca3af;border-top:1px solid #e5e7eb;}
</style>
</head>
<body>
<div class="container">
    <div class="header">
        <h1>&#128737; VulnSight Scan Report</h1>
        <p>Target: {{ $targets }} &nbsp;&middot;&nbsp; Scan ID: {{ $scanId }} &nbsp;&middot;&nbsp; {{ $startedAt }}</p>
    </div>
    <div class="summary">
        <div class="stat"><div class="stat-num" style="color:#111827;">{{ count($vulns) }}</div><div class="stat-lbl">Total</div></div>
        <div class="stat"><div class="stat-num" style="color:#dc2626;">{{ $counts['critical'] }}</div><div class="stat-lbl">Critical</div></div>
        <div class="stat"><div class="stat-num" style="color:#ea580c;">{{ $counts['high'] }}</div><div class="stat-lbl">High</div></div>
        <div class="stat"><div class="stat-num" style="color:#ca8a04;">{{ $counts['medium'] }}</div><div class="stat-lbl">Medium</div></div>
        <div class="stat"><div class="stat-num" style="color:#16a34a;">{{ $counts['low'] }}</div><div class="stat-lbl">Low</div></div>
    </div>
    <div class="section">
        <h2>Vulnerabilities</h2>
        <table>
            <thead>
                <tr><th>Vulnerability</th><th>Endpoint</th><th>Severity</th><th>Status</th></tr>
            </thead>
            <tbody>
            @foreach($vulns as $v)
            <tr>
                <td><strong>{{ $v['name'] ?? $v['type'] ?? '—' }}</strong></td>
                <td style="font-family:monospace;color:#059669;font-size:12px;">{{ $v['url'] ?? $v['endpoint'] ?? '—' }}</td>
                <td><span class="badge badge-{{ strtolower($v['severity'] ?? $v['sev'] ?? 'low') }}">{{ strtoupper($v['severity'] ?? $v['sev'] ?? 'low') }}</span></td>
                <td>{{ $v['status'] ?? 'open' }}</td>
            </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    <div class="footer">Generated by VulnSight &nbsp;&middot;&nbsp; {{ now()->format('M d, Y H:i') }}</div>
</div>
</body>
</html>
